services:
  backend_dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: springboot-dev
    working_dir: /app
    volumes:
      - ./backend/:/app # Mount source code into container
      - ~/.m2:/root/.m2 # Cache maven deps between container runs
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

  web_dev:
    build:
      context: ./webpage
      dockerfile: Dockerfile
    volumes:
      - ./webpage:/app # Mount source code
      - /app/node_modules # Prevent node_modules override
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

  db_dev:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  flyway_dev:
    image: flyway/flyway:latest
    restart: on-failure
    container_name: flyway-dev
    depends_on:
      - db_dev
    volumes:
      - ./db/migrations:/flyway/sql
    env_file:
      - .env
    command: -baselineOnMigrate=true migrate
    environment:
      - FLYWAY_URL=jdbc:mysql://db_dev:3306/${MYSQL_DATABASE}
      - FLYWAY_USER=${MYSQL_USER}
      - FLYWAY_PASSWORD=${MYSQL_PASSWORD}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql/versioned,filesystem:/flyway/sql/repeatable

volumes:
  mysql_data:

